name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
      - name: Setup environment
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit and push changes
        run: |
          git checkout gh-pages
          git add -A
          git commit -m "Build pages"
          git push origin gh-pages
