name: Incident Management
on:
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created, deleted, edited]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync-issues-to-incidents:
    runs-on: ubuntu-latest
    steps:
      - run: echo "event name is:" ${{ github.event_name }}
      - run: echo "event type is:" ${{ github.event.action }}
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scripts/requirements.txt
      - name: Sync issues
        env:
          ACCESS_PAT: ${{ secrets.ACCESS_PAT }}
        run: python ./scripts/sync_issues.py
      - name: Setup environment
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "Sync issues to incident"
          git push origin main
