name: Status Monitor
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/90 * * * *"
  # issues:
  #   types: [opened, edited, closed, reopened, labeled, unlabeled]
  # issue_comment:
  #   types: [created, deleted, edited]
jobs:
  status-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scripts/requirements.txt
      - name: Sync issues
        env:
          ACCESS_PAT: ${{ secrets.ACCESS_PAT }}
        run: python ./scripts/monitor.py
